Repository Seneca-CDOT/Osteppy, pull requests merged in 2021-05, with the labels that each got.

#55 Add settings for development and production deployment
  development.yml
  docker-compose.yml
  env.example
  production.yml
  src/app.module.ts
Labels: area: develop

#56 Enable prettier as eslint rules
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  src/Users/users.service.ts
  test/app.e2e-spec.ts
Labels: area: develop, type: enhancement

#57 Add authentication
  .eslintrc.json
  env.example
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/authentication.guard.ts
  src/body_parser.middleware.ts
  src/main.ts
  src/types/slack.d.ts
Labels: area: develop, type: enhancement

#58 Add basic routes
  .eslintrc.json
  package-lock.json
  package.json
  src/Users/users.service.ts
  src/app.controller.ts
  src/app.module.ts
  src/authentication.guard.ts
  src/body_parser.middleware.ts
  src/configuration.ts
  src/dev/dev.controller.ts
  src/dev/dev.module.ts
  src/dev/dev.service.ts
  src/dto/slack_request.dto.ts
  src/eod/eod.controller.ts
  src/eod/eod.module.ts
  src/eod/eod.service.ts
  src/main.ts
  src/types/slack.d.ts
  src/user/dto/create-user.dto.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: area: develop, type: enhancement

#59 Add eod submitting endpoint
  .eslintrc.json
  package-lock.json
  package.json
  src/app.module.ts
  src/dto/slack_block_divider.dto.ts
  src/dto/slack_block_section.dto.ts
  src/dto/slack_request.dto.ts
  src/dto/slack_response.dto.ts
  src/dto/slack_text_object.dto.ts
  src/eod/eod.controller.ts
  src/eod/eod.module.ts
  src/eod/eod.service.ts
  src/user/schemas/user.schema.ts
  src/user/user.service.ts
Labels: area: develop, type: enhancement

#60 Fix: missing environment variables in production docker-compose file
  production.yml
Labels: area: develop, type: bug

#63 Set time zone for containers
  docker-compose.yml
  env.example
  production.yml
Labels: area: develop, type: bug, type: enhancement
