Repository Seneca-CDOT/Osteppy, pull requests merged in 2021-08, with the labels that each got.

#69 Fix: missing environment variable
  production.yml
Labels: type: bug, area: develop

#70 Add unit testing to the current ci
  .github/workflows/ci.yml
  .github/workflows/run_linter.yml
Labels: priority: medium, difficulty: medium, area: develop, area: ci

#71 Add queue eod
  src/slack/slack_eods.controller.ts
  src/slack/slack_eods.service.ts
  src/users/users.service.ts
Labels: type: enhancement, area: develop

#72 Add port checking functionality
  config_files/domains.example.json
  env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/configuration.ts
  src/main.ts
  src/system/system.controller.ts
  src/system/system.module.ts
  src/system/system.service.spec.ts
  src/system/system.service.ts
  src/system/system_domains.d.ts
  src/system/system_services.d.ts
Labels: priority: medium, difficulty: medium, type: enhancement, area: develop

#73 Switch from node-schedule to nestjs/scheduler and fix production deployment
  Dockerfile
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/system/system.service.ts
  src/users/users_eods.service.ts
Labels: priority: medium, difficulty: starter, type: enhancement, area: develop

#76 Add Portainer in production
  .dockerignore
  .gitignore
  production.yml
Labels: priority: medium, difficulty: medium, type: enhancement, area: develop, area: docker

#80 Add /list-ports command
  src/slack/slack.module.ts
  src/slack/slack_system.controller.ts
  src/slack/slack_system.service.ts
Labels: priority: medium, type: enhancement, area:system

#82 feat: add mongo express in development
  development.yml
  docker-compose.yml
Labels: priority: medium, difficulty: starter, type: enhancement, area: docker
